---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'S3 bucket contains HTML files of static website'

Resources:
  MyBucket:
    Type: AWS::S3::Bucket
    Properties: 
      AccessControl: PublicReadWrite
    