---
AWSTemplateFormatVersion: '2010-09-09'
Description: 'Resources related to security'

Resources:
  WebSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow web users to access
      SecurityGroupIngress:
      - CidrIp: 0.0.0.0/0
        Description: Allow HTTP access
        FromPort: 80
        IpProtocol: tcp
        ToPort: 80

Outputs:
  WebAccessFirewall:
    Value: !Ref WebSecurityGroup
    Export:
      Name: WebAccess